### ISSUE TITLE
Getting this on a Raspberry Pi 3

### ISSUE THREAD

**Issue by jishindev** [Galarzaa90/android-things-rc522#7]
Process: com.creoit.android.rfidtest, PID: 2743
    java.lang.IncompatibleClassChangeError: Found interface com.google.android.things.pio.SpiDevice, but class was expected (declaration of 'com.google.android.things.pio.SpiDevice' appears in /system/framework/com.google.android.things.jar)
        at com.galarzaa.androidthings.Rc522.initializePeripherals(Rc522.java:124)
        at com.galarzaa.androidthings.Rc522.<init>(Rc522.java:116)
        at com.creoit.android.rfidtest.MainActivity.onCreate(MainActivity.kt:51)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Activity.performCreate(Activity.java:6991)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by vudzkostek** [comment]
You probably compile it for newer android things preview version. library is compiled with 0.2-devpreview PROVIDED and when installed on device app will use system libraries that could not be the same (if you already updated board image). I posted pull request with things library update to 0.7-devpreview.

**Comment by jishindev** [comment]
Oh, I see. Thanks for the response. Will checkout your PR.

**Comment by vudzkostek** [comment]
Already tested and works fine using NXP board.

**Comment by Galarzaa90** [comment]
This was fixed in PR #8
